FROM mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Services/Order/Free.Course.Services.Order.Application/*.csproj Services/Order/Free.Course.Services.Order.Application/
COPY Services/Order/Free.Course.Services.Order.Domain.Core/*.csproj Services/Order/Free.Course.Services.Order.Domain.Core/
COPY Services/Order/Free.Course.Services.Order.Infrastructure/*.csproj Services/Order/Free.Course.Services.Order.Infrastructure/
COPY Services/Order/Free.Courser.Services.Domain/*.csproj Services/Order/Free.Courser.Services.Domain/
COPY Services/Order/Free.Course.Services.Order.API/*.csproj Services/Order/Free.Course.Services.Order.API/
RUN dotnet restore Services/Order/Free.Course.Services.Order.API/*.csproj 
COPY . .
RUN dotnet publish Services/Order/Free.Course.Services.Order.API/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bookworm-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","Free.Course.Services.Order.API.dll" ]