FROM mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim as build
WORKDIR /app
EXPOSE 80
COPY Free.Course.Gateway/*.csproj Free.Course.Gateway/
RUN dotnet restore Free.Course.Gateway/*.csproj
COPY . .
RUN dotnet publish Free.Course.Gateway/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bookworm-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","Free.Course.Gateway.dll" ]