FROM mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Services/Basket/Free.Course.Services.Basket/*.csproj Services/Basket/Free.Course.Services.Basket/
RUN dotnet restore Services/Basket/Free.Course.Services.Basket/*.csproj 
COPY . .
RUN dotnet publish Services/Basket/Free.Course.Services.Basket/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bookworm-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","Free.Course.Services.Basket.dll" ]