FROM mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Frontends/Free.Course.Web/*.csproj Frontends/Free.Course.Web/
RUN dotnet restore Frontends/Free.Course.Web/*.csproj
COPY . .
RUN dotnet publish Frontends/Free.Course.Web/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bookworm-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","Free.Course.Web.dll" ]