FROM mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Services/FakePayment/Free.Course.Services.FakePayment/*.csproj Services/FakePayment/Free.Course.Services.FakePayment/
RUN dotnet restore Services/FakePayment/Free.Course.Services.FakePayment/*.csproj 
COPY . .
RUN dotnet publish Services/FakePayment/Free.Course.Services.FakePayment/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bookworm-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","Free.Course.Services.FakePayment.dll" ]